#!/bin/bash
# Collect Jetson Orin Nano hardware information and save to markdown

OUTPUT_FILE="${1:-Jetson_Hardware.md}"

{
  echo "# Jetson Orin Nano Hardware Info"
  echo ""
  echo "**Collected:** $(date)"
  echo "**System:** $(hostname)"
  echo ""
  echo "---"
  echo ""
  echo "## Platform Info"
  echo ""
  echo "**Kernel:**"
  echo "\`\`\`"
  uname -a
  echo "\`\`\`"
  echo ""
  echo "**OS:**"
  echo "\`\`\`"
  lsb_release -a 2>/dev/null || echo "Not available"
  echo "\`\`\`"
  echo ""
  echo "**Device Model:**"
  echo "\`\`\`"
  cat /proc/device-tree/model 2>/dev/null || echo "Not available"
  echo "\`\`\`"
  echo ""
  echo "**L4T/JetPack Version:**"
  echo "\`\`\`"
  cat /etc/nv_tegra_release 2>/dev/null || echo "Not available"
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## CPU & Memory"
  echo ""
  echo "**CPU Info:**"
  echo "\`\`\`"
  grep -m 1 "model name" /proc/cpuinfo
  echo "Cores: $(grep -c '^processor' /proc/cpuinfo)"
  echo "\`\`\`"
  echo ""
  echo "**Memory:**"
  echo "\`\`\`"
  free -h
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## Storage"
  echo ""
  echo "**Disk Layout:**"
  echo "\`\`\`"
  lsblk -f
  echo "\`\`\`"
  echo ""
  echo "**Free Space:**"
  echo "\`\`\`"
  df -h /
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## GPU & NVIDIA"
  echo ""
  echo "**NVIDIA GPU:**"
  echo "\`\`\`"
  jetson_release 2>/dev/null | grep -A 5 -i gpu || echo "Not available"
  echo "\`\`\`"
  echo ""
  echo "**CUDA:**"
  echo "\`\`\`"
  which nvcc >/dev/null 2>&1 && nvcc --version || echo "CUDA toolkit not found"
  echo "\`\`\`"
  echo ""
  echo "**cuDNN:**"
  echo "\`\`\`"
  dpkg -l | grep -i cudnn || echo "Not found"
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## Cameras"
  echo ""
  echo "**Available Cameras:**"
  echo "\`\`\`"
  v4l2-ctl --list-devices 2>/dev/null || echo "v4l2-ctl not available; run: sudo apt install v4l-utils"
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## Network Interfaces"
  echo ""
  echo "**Network Devices:**"
  echo "\`\`\`"
  ip addr show
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## USB Devices"
  echo ""
  echo "**USB Devices:**"
  echo "\`\`\`"
  lsusb
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## PCI Devices (Wireless/Network)"
  echo ""
  echo "**PCI Network/Wireless:**"
  echo "\`\`\`"
  lspci -nn | grep -iE 'network|wireless|wifi|ethernet' || echo "No matches found"
  echo "\`\`\`"
} > "$OUTPUT_FILE"

echo "Hardware info saved to: $OUTPUT_FILE"
